// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function GetLastError() {
  return window['go']['main']['App']['GetLastError']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetStorageDir() {
  return window['go']['main']['App']['GetStorageDir']();
}

export function NewTab() {
  return window['go']['main']['App']['NewTab']();
}

export function RenameTab(arg1, arg2) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2);
}

export function SaveTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTab'](arg1, arg2, arg3);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}
