// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CloseTab(arg1:number):Promise<core.State>;

export function GetLastError():Promise<string>;

export function GetState():Promise<core.State>;

export function GetStorageDir():Promise<string>;

export function NewTab():Promise<core.State>;

export function RenameTab(arg1:number,arg2:string):Promise<core.State>;

export function SaveTab(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SetActiveTab(arg1:number):Promise<core.State>;
